### ISSUE TITLE
Tap_action: request

### ISSUE THREAD

**Issue by Doghousestaffs** [Makin-Things/platinum-weather-card#48] opened 2022-08-15 09:44 UTC
It would be great to have a tap_action: ability for this card, even if it’s just a tap_action: for the whole card and not for the individual sensors within the card, say the ability to show only a basic forecast and you could use the tap_action with browser mod or to navigate to another page with a more detailed forecast.

**Comment by catchdave** [comment] 2022-08-25 00:54
+1

I have multiple dashboards and have a small summary on the home screen and need to be able to have the tap navigate to the detailed weather screen.

Most custom cards and built-in cards already support this (https://www.home-assistant.io/dashboards/actions/#tap-action). I was actually surprised to not see support for `tap_action`

**Comment by Makin-Things** [comment] 2022-09-18 08:09
This is not going to happen any time soon as I have to many other things on my plate. I also don't fully understand what you are asking for. The card is detailed, what other details are there to include in a pop up window?

**Comment by Doghousestaffs** [comment] 2022-09-18 08:12
Well clearly if it had a pop up window it would operate the same as any other pop up in HA, it would display the history if it was a sensor, if it was weather days then it would display more days and more info, or you could make it navigate to another page or pop up with a more detailed weather view..
________________________________

**Comment by catchdave** [comment] 2022-09-21 19:46
@Makin-Things. Totally understand there's lots to do.

To answer your question, there are many use cases. My use case is that I have multiple dashbaords on a tablet. I use a small version of the weather card on my main dashboard. I have an entire dashboard that has the full platinum weather card, and I want to be able to tap on the reduced version to take you to the full version.

On my main dashboard, I have a card that just has the current temp - and I want to be able to click it to take me a second dashboard that has the full details.

I have attached the two dashboards as examples:
Main Dashboard:
![Screen Shot 2022-09-21 at 12 42 28 PM](https://user-images.githubusercontent.com/823598/191596481-c942d868-e72f-441c-bf1e-622954baab52.png)
 
Detailed weather screen:
![Screen Shot 2022-09-21 at 12 44 31 PM](https://user-images.githubusercontent.com/823598/191596557-c461d5f5-e8f2-4583-9aa0-c7f830da10bf.png)

**Comment by Makin-Things** [comment] 2022-09-21 22:19
@catchdave So if I understand correctly you want to tap on another card (not the platinum-weather-card) and have the platinum card pop up.
I am not sure if that is possible, but it would be the tap action of the other card that would need to implement the feature.

**Comment by Makin-Things** [comment] 2022-09-21 22:22
@Doghousestaffs well if you are using an integration that provides a weather.xxx type entity there is no history to show. Those entities have all the values stored in attributes, which HA does not keep a history of (only states have history).

**Comment by catchdave** [comment] 2022-09-22 03:01
@Makin-Things : Not quite. I have multiple platinum cards. On the home dashboard, I have a platinum card with just the max temp. I want to "click on the platinum card" and have that goto another dashboard (that second dashboard happens to have a more detailed platinum card).

I can do the what I want with every other card because they all support `tap_action`. The platinum card is the only one I am using that does not.

**Comment by OCT0PUSCRIME** [comment] 2022-09-27 20:01
+1

I currently use Browser Mod to open a Radar when tapping on the normal weather card that is included with HomeAssistant and cannot do so on Platinum because there is no Tap_Action.

Here is a screenshot of what pops when tapping the normal weather card:

![09-27-2022-15-58-15_chrome](https://user-images.githubusercontent.com/65912221/192623836-1c4b6f46-1cda-47fe-9551-18ee676c8296.png)

and the YAML:

`
type: weather-forecast
entity: weather.home
hold_action:
  action: more-info
tap_action:
  action: fire-dom-event
  browser_mod:
    service: browser_mod.popup
    data:
      title: Radar
      content:
        type: iframe
        url: >-
          HTTPS://[URL for Radar]
        aspect_ratio: 100%
`

**Comment by Makin-Things** [comment] 2022-09-28 01:06
A beta 0.0.5b2 has the ability to use tap/hold actions. At the moment they have to be configured in yaml mode as trying to figure out how to add them to the editor will be challenging. You have probably noticed that there are almost zero custom cards that provide a graphical editor as it is ridiculously painful to implement.
At the moment double tap is not an option as that is broken/not implemented in the very limited sample code provided in the boilerplate-card.
The config options in yaml are the same as any other card that supports actions.

**Comment by OCT0PUSCRIME** [comment] 2022-10-01 16:09
> A beta 0.0.5b2 has the ability to use tap/hold actions. At the moment they have to be configured in yaml mode as trying to figure out how to add them to the editor will be challenging. You have probably noticed that there are almost zero custom cards that provide a graphical editor as it is ridiculously painful to implement. At the moment double tap is not an option as that is broken/not implemented in the very limited sample code provided in the boilerplate-card. The config options in yaml are the same as any other card that supports actions.

Thanks! I can confirm tap_action works in beta.

**Comment by Makin-Things** [comment] 2022-10-01 22:04
Cool. I will close this once 0.0.5 is release (should be in the next few days).

**Comment by Makin-Things** [comment] 2022-10-19 00:14
Closing as it is included in release 1.0.0

**Closed by Makin-Things** 2022-10-19 00:14 UTC
Labels: enhancement

**Comment by kdober** [comment] 2024-03-02 23:06
Hi, I'm sorry to open a question on this closed ticket. But it is related to the topic.
Could you give an example how to use the tap or hold actions?
I'm currently trying this on the yalm 

`        tap_action:
          entity: weather.home
          action: more-info`
          
or just 

`        tap_action:
          action: more-info
`          

My idea is that when clicking on the tablet screen, it will open all the entity information. Similar as it happens on the 'bramkragten' weather card.
Is this even possible?
I even try this (i have browser_mod installed), but without luck.

`tap_action:
  action: fire-dom-event
  browser_mod:
    service: browser_mod.more-info
    data:
      entity: weather.home`

I'm able to do other type of actions, like navigate to another dashboard.

Any help is appreciated.
Cheers
Cristian

**Comment by Doghousestaffs** [comment] 2024-03-03 10:03
Hi Cristian.

Do it like

“entity: weather.tomorrow_io_home_daily
tap_action:
  action: more-info”

Your probably missing the entity part, just change that to the entity you want more info for.

Hope that helps.
________________________________
