### ISSUE TITLE
Correct Timestamp Format

### ISSUE THREAD

**Issue by VAFS001** [Makin-Things/platinum-weather-card#35] opened 2022-07-20 20:26 UTC
I have everything working great on your card however I receive the following date error with several different timestamp formats:

I have tried epochtime, 20.07.2022T08:30, and nothing seems to work.

![image](https://user-images.githubusercontent.com/17306997/180074851-7415369d-4f24-4f08-ac4f-542c8dd6355e.png)

Someone clue me in to the correct timestamp to use here? I can make this sensor fit into the format:
![image](https://user-images.githubusercontent.com/17306997/180075021-d01d9166-eb62-4c0d-bb4d-aea6d1cea494.png)

I don't see an example of a valid timestamp as described here:
<html>
<body>

Entity Update Time | Entity | Defines the entity to use for the timestamp. The entities state MUST provide a valid timestamp
-- | -- | --

</body>
</html>

If I missed it, I apologize in advance.

Thank you.

**Comment by Makin-Things** [comment] 2022-07-20 23:28
HA uses an ISO standard (I can't remember the number of the top of my head). But they have this format. I am still working my way through the documentation, so people mentioning omissions in the parts I think I have done is good. I'll find the ISO number and put a reference and the format in the readme shortly.

![image](https://user-images.githubusercontent.com/91187456/180099267-5ffb70d4-dc23-41d8-a29e-39ff1b4a8932.png)

Let me know if you still have problems.

**Comment by Makin-Things** [comment] 2022-07-20 23:41
It wasn't an ISO standard, but RFC 3339 that the HA devs use. I have updated the table in the readme for the title section to include a mention of this and show the format that is expected.

**Comment by VAFS001** [comment] 2022-07-21 00:43
Thank you for the quick reply. I will try it out. I just need to figure out how to get this timestamp out of an epoch.

**Comment by Makin-Things** [comment] 2022-07-21 01:06
Awesome. I was just going to post how to do it in a template. I'll add it here anyway just in case someone else comes across this issue.
In a template you can convert a unix epoch to a timestamp by using the following
```{{ 1658365033 | timestamp_local }}```
Feel free to add your solution and close if the issue is resolved.

**Comment by Makin-Things** [comment] 2022-07-22 10:10
Closing as I think this has been addressed. Reopen if needed.

**Closed by Makin-Things** 2022-07-22 10:10 UTC
Labels: documentation, question
